name: environmentTests
run-name: ${{github.workflow}}.branch_${{github.ref_name}}.${{github.event_name}}.${{github.run_attempt}}

on:
  workflow_dispatch:

#required for workload federation with Azure
permissions:
  id-token: write
  contents: read

env:
  templateFile: ./environmentTests/main.bicep
  devWorkloadIdentityAppID: 232b31e9-6f27-49f8-b9ec-5b6b1f3ceb8a
  prdWorkloadIdentityAppID: 2b10c58e-fd7c-4599-adfc-205c68e9e79d
  workloadIdentitySubID: 7a86d903-0585-40e1-8af9-92a5efc19c1c
  workloadIdentityTenantID: 43545180-b7d6-410f-8328-eacfc8b660ea
  devDeploymentsJson: > 
        [
            {
              "environment": "environmentTests-prd",
              "templateParameterFile": "./environmentTests/main.prd.bicepparam",
              "resourceGroupName": "environmentTests-prd",
              "subscriptionId": "7a86d903-0585-40e1-8af9-92a5efc19c1c"
            }
        ]
  prdDeploymentsJson: > 
        [
            {
              "environment": "environmentTests-prd",
              "templateParameterFile": "./environmentTests/main.prd.bicepparam",
              "resourceGroupName": "environmentTests-prd",
              "subscriptionId": "7a86d903-0585-40e1-8af9-92a5efc19c1c"
            }
        ]

jobs:
  initVariables:
    name: Initialize Variables
    runs-on: ubuntu-latest
    outputs:
      templateFile: ${{env.templateFile}}
      devDeploymentsJson: ${{env.devDeploymentsJson}}
      prdDeploymentsJson: ${{env.prdDeploymentsJson}}
      devWorkloadIdentityAppID: ${{env.devWorkloadIdentityAppID}}
      prdWorkloadIdentityAppID: ${{env.prdWorkloadIdentityAppID}}
      workloadIdentitySubID: ${{env.workloadIdentitySubID}}
      workloadIdentityTenantID: ${{env.workloadIdentityTenantID}}
      deploymentName: ${{steps.set_variables.outputs.deploymentName}}
    steps:
      - name: Set string manipulated variables
        id: set_variables
        run: |
          echo "Exposing environment variables due to limitation in reusable workflows"
          currentDate=$(date +"%Y%m%d-%H%M")
          deploymentName=$(echo "${{github.workflow}}.$currentDate" | tr -d ' ')
          echo "deploymentName: $deploymentName"
          echo "deploymentName=$deploymentName" >> $GITHUB_OUTPUT
        shell: bash

  validateDev:
    strategy:
      fail-fast: false # ensures that other validate jobs can finish instead of getting interrupted by a single failure
      matrix:
          deploymentsJson: ${{ fromJson(needs.initVariables.outputs.devDeploymentsJson)}}
    
    name: Validate ${{matrix.deploymentsJson.environment}}
    needs: initVariables
    uses: abkgaard/workflowTemplates/.github/workflows/AzureRGValidation_env.yml@main
    with:
      environment: ${{matrix.deploymentsJson.environment}}
      templateFile: ${{needs.initVariables.outputs.templateFile}}
      templateParameterFile: ${{matrix.deploymentsJson.templateParameterFile}}
      resourceGroupName: ${{matrix.deploymentsJson.resourceGroupName}}
      subscriptionId: ${{matrix.deploymentsJson.subscriptionId}}
      deploymentName: ${{needs.initVariables.outputs.deploymentName}}
      workloadIdentityAppId: ${{needs.initVariables.outputs.devWorkloadIdentityAppID}}
      workloadIdentitySubId: ${{needs.initVariables.outputs.workloadIdentitySubID}}
      workloadIdentityTenantId: ${{needs.initVariables.outputs.workloadIdentityTenantID}}
  
  validatePrd:
    if: contains('refs/heads/main', github.ref)
    strategy:
      fail-fast: false # ensures that other validate jobs can finish instead of getting interrupted by a single failure
      matrix:
          deploymentsJson: ${{ fromJson(needs.initVariables.outputs.prdDeploymentsJson)}}
    
    name: Validate ${{matrix.deploymentsJson.environment}}
    needs: initVariables
    uses: abkgaard/workflowTemplates/.github/workflows/AzureRGValidation_env.yml@main
    with:
      environment: ${{matrix.deploymentsJson.environment}}
      templateFile: ${{needs.initVariables.outputs.templateFile}}
      templateParameterFile: ${{matrix.deploymentsJson.templateParameterFile}}
      resourceGroupName: ${{matrix.deploymentsJson.resourceGroupName}}
      subscriptionId: ${{matrix.deploymentsJson.subscriptionId}}
      deploymentName: ${{needs.initVariables.outputs.deploymentName}}
      workloadIdentityAppId: ${{needs.initVariables.outputs.prdWorkloadIdentityAppID}}
      workloadIdentitySubId: ${{needs.initVariables.outputs.workloadIdentitySubID}}
      workloadIdentityTenantId: ${{needs.initVariables.outputs.workloadIdentityTenantID}}

  deployDev:
    strategy:
      fail-fast: false # ensures that other deploy jobs can finish instead of getting interrupted by a single failure
      matrix:
          deploymentsJson: ${{ fromJson(needs.initVariables.outputs.devDeploymentsJson)}}
    
    name: Deploy ${{matrix.deploymentsJson.environment}}
    needs: [initVariables, validateDev]
    uses: abkgaard/workflowTemplates/.github/workflows/AzureRGDeployment_env.yml@main
    with:
      environment: ${{matrix.deploymentsJson.environment}}
      templateFile: ${{needs.initVariables.outputs.templateFile}}
      templateParameterFile: ${{matrix.deploymentsJson.templateParameterFile}}
      resourceGroupName: ${{matrix.deploymentsJson.resourceGroupName}}
      subscriptionId: ${{matrix.deploymentsJson.subscriptionId}}
      deploymentName: ${{needs.initVariables.outputs.deploymentName}}
      workloadIdentityAppId: ${{needs.initVariables.outputs.devWorkloadIdentityAppID}}
      workloadIdentitySubId: ${{needs.initVariables.outputs.workloadIdentitySubID}}
      workloadIdentityTenantId: ${{needs.initVariables.outputs.workloadIdentityTenantID}}

  deployPrd:
    if: contains('refs/heads/main', github.ref)
    strategy:
      fail-fast: false # ensures that other deploy jobs can finish instead of getting interrupted by a single failure
      matrix:
          deploymentsJson: ${{ fromJson(needs.initVariables.outputs.devDeploymentsJson)}}
    
    name: Deploy ${{matrix.deploymentsJson.environment}}
    needs: [initVariables, validatePrd]
    uses: abkgaard/workflowTemplates/.github/workflows/AzureRGDeployment_env.yml@main
    with:
      environment: ${{matrix.deploymentsJson.environment}}
      templateFile: ${{needs.initVariables.outputs.templateFile}}
      templateParameterFile: ${{matrix.deploymentsJson.templateParameterFile}}
      resourceGroupName: ${{matrix.deploymentsJson.resourceGroupName}}
      subscriptionId: ${{matrix.deploymentsJson.subscriptionId}}
      deploymentName: ${{needs.initVariables.outputs.deploymentName}}
      workloadIdentityAppId: ${{needs.initVariables.outputs.prdWorkloadIdentityAppID}}
      workloadIdentitySubId: ${{needs.initVariables.outputs.workloadIdentitySubID}}
      workloadIdentityTenantId: ${{needs.initVariables.outputs.workloadIdentityTenantID}}